# Generated by Django 4.1.5 on 2023-01-11 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housetype', models.TextField(choices=[('Apartment', 'Apartment'), ('Compound', 'Compound'), ('Room', 'Room'), ('Condominium', 'Condominium'), ('Luxury', 'Luxury')], default='Room', max_length=255, null=True)),
                ('numRoom', models.IntegerField(null=True)),
                ('kebele', models.IntegerField(null=True)),
                ('city', models.TextField(choices=[('AddisAbaba', 'AddisAbaba'), ('Bahirdar', 'Bahirdar'), ('DireDawa', 'DireDawa'), ('Harar', 'Harar'), ('Mekele', 'Mekele'), ('Other', 'Other')], default='Other', max_length=100)),
                ('area', models.FloatField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('floor', models.IntegerField(default=0, null=True)),
                ('landlordName', models.TextField(max_length=255, null=True)),
                ('landlordPhone', models.TextField(max_length=20, null=True)),
                ('houseStatus', models.TextField(choices=[('Available', 'Available'), ('Rented', 'Rented')], default='Available', max_length=100)),
                ('title', models.TextField(max_length=255, null=True)),
                ('image', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('tags', models.ManyToManyField(to='webapp.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='profile1.png', null=True, upload_to='')),
                ('email', models.TextField(max_length=255)),
                ('phone', models.TextField(max_length=11, null=True)),
                ('kebeleID', models.TextField(default=0, max_length=10, null=True)),
                ('city', models.TextField(choices=[('AddisAbaba', 'AddisAbaba'), ('Bahirdar', 'Bahirdar'), ('DireDawa', 'DireDawa'), ('Harar', 'Harar'), ('Mekele', 'Mekele'), ('Other', 'Other')], default='Other', max_length=100)),
                ('job', models.TextField(max_length=255, null=True)),
                ('fullName', models.TextField(max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
