# Generated by Django 4.1.5 on 2023-01-09 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('password', models.CharField(max_length=255)),
                ('kebeleID', models.CharField(default=0, max_length=10, null=True)),
                ('region', models.CharField(choices=[('AddisAbaba', 'AddisAbaba'), ('Amhara', 'Amhara'), ('DireDawa', 'DireDawa'), ('Harari', 'Harari'), ('Oromia', 'Oromia'), ('Tigray', 'Tigray')], max_length=100)),
                ('city', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseID', models.IntegerField()),
                ('housetype', models.CharField(choices=[('Apartment', 'Apartment'), ('Compound', 'Compound'), ('Room', 'Room'), ('Condominium', 'Condominium'), ('Luxury', 'Luxury')], max_length=255, null=True)),
                ('region', models.CharField(choices=[('AddisAbaba', 'AddisAbaba'), ('Amhara', 'Amhara'), ('DireDawa', 'DireDawa'), ('Harari', 'Harari'), ('Oromia', 'Oromia'), ('Tigray', 'Tigray')], max_length=100)),
                ('city', models.CharField(max_length=255, null=True)),
                ('area', models.FloatField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('floor', models.IntegerField(default=0, null=True)),
                ('landlordName', models.CharField(max_length=255, null=True)),
                ('landlordPhone', models.CharField(max_length=255, null=True)),
                ('houseStatus', models.CharField(choices=[('Available', 'Available'), ('Rented', 'Rented')], default='Available', max_length=200)),
                ('pic', models.FileField(default='', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('category', models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('tags', models.ManyToManyField(to='webapp.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200, null=True)),
                ('note', models.CharField(max_length=100, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.product')),
            ],
        ),
    ]
