# Generated by Django 4.1.5 on 2023-01-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(choices=[('AddisAbaba', 'AddisAbaba'), ('Bahirdar', 'Bahirdar'), ('DireDawa', 'DireDawa'), ('Harar', 'Harar'), ('Mekele', 'Mekele'), ('Other', 'Other')], default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='fullName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='job',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='kebeleID',
            field=models.CharField(default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='city',
            field=models.CharField(choices=[('AddisAbaba', 'AddisAbaba'), ('Bahirdar', 'Bahirdar'), ('DireDawa', 'DireDawa'), ('Harar', 'Harar'), ('Mekele', 'Mekele'), ('Other', 'Other')], default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='house',
            name='houseStatus',
            field=models.CharField(choices=[('Available', 'Available'), ('Rented', 'Rented')], default='Available', max_length=100),
        ),
        migrations.AlterField(
            model_name='house',
            name='housetype',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('Compound', 'Compound'), ('Room', 'Room'), ('Condominium', 'Condominium'), ('Luxury', 'Luxury')], default='Room', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='landlordName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='landlordPhone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
