# Generated by Django 4.1.5 on 2023-01-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_customer_city_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image',
            field=models.ImageField(blank=True, default='images/Uploads/image-placeholder-500x500.jpg', upload_to='images/Uploads/'),
        ),
    ]
