# Generated by Django 4.1.5 on 2023-01-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_house_rental_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='rental_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
