# Generated by Django 4.1.5 on 2023-01-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_address_customer_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='houseStatus',
            field=models.CharField(choices=[('Available', 'Available'), ('Rented', 'Rented')], default='Available', max_length=100),
        ),
        migrations.AlterField(
            model_name='house',
            name='landlordPhone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
