# Generated by Django 4.1.5 on 2023-01-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_image_remove_house_pic_remove_order_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('featured', models.ImageField(null=True, upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='fullName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
