# Generated by Django 4.1.5 on 2023-01-10 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0010_product2_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housetype', models.CharField(choices=[('Apartment', 'Apartment'), ('Compound', 'Compound'), ('Room', 'Room'), ('Condominium', 'Condominium'), ('Luxury', 'Luxury')], default='Room', max_length=255, null=True)),
                ('numRoom', models.IntegerField(null=True)),
                ('kebele', models.IntegerField(null=True)),
                ('city', models.CharField(choices=[('AddisAbaba', 'AddisAbaba'), ('Bahirdar', 'Bahirdar'), ('DireDawa', 'DireDawa'), ('Harar', 'Harar'), ('Mekele', 'Mekele'), ('Other', 'Other')], default='Other', max_length=100)),
                ('area', models.FloatField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('floor', models.IntegerField(default=0, null=True)),
                ('landlordName', models.CharField(max_length=255, null=True)),
                ('landlordPhone', models.CharField(max_length=20, null=True)),
                ('houseStatus', models.CharField(choices=[('Available', 'Available'), ('Rented', 'Rented')], default='Available', max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='transaction_id',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_ordered',
        ),
        migrations.AddField(
            model_name='customer',
            name='about',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(choices=[('AddisAbaba', 'AddisAbaba'), ('Bahirdar', 'Bahirdar'), ('DireDawa', 'DireDawa'), ('Harar', 'Harar'), ('Mekele', 'Mekele'), ('Other', 'Other')], default='Other', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='fullName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='job',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='kebeleID',
            field=models.CharField(default=0, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pic',
            field=models.FileField(default='', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.customer'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Product2',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
        migrations.AddField(
            model_name='house',
            name='tags',
            field=models.ManyToManyField(to='webapp.tag'),
        ),
        migrations.AddField(
            model_name='order',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.house'),
        ),
        migrations.AddField(
            model_name='order',
            name='tags',
            field=models.ManyToManyField(to='webapp.tag'),
        ),
    ]
